name: PR Autolabeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  autolabel:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Autolabel PR
        uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
