name: Release Autolabeler

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  release-autolabeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Autolabel for Release
        uses: release-drafter/release-drafter/autolabeler@v7
